# Generated by Django 5.1.1 on 2024-09-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_user_id_listing_comment_bid_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='starting_bid',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('ELE', 'Electronics'), ('FAS', 'Fashion'), ('HOM', 'Home'), ('TOY', 'Toys'), ('ART', 'Art'), ('INS', 'Musical Instruments')], max_length=32),
        ),
    ]
